# Generated by Django 4.2 on 2024-02-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_user_is_admin_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
