# Generated by Django 4.2 on 2024-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_remove_user_is_admin_remove_user_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=100, null=True),
        ),
    ]
