# Generated by Django 4.2 on 2024-02-16 11:00

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0019_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
