# Generated by Django 4.2 on 2024-04-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Personal Chat'},
        ),
    ]
